set_property PACKAGE_PIN M20 [get_ports B_Serial]
set_property PACKAGE_PIN P26 [get_ports A_Serial]
set_property PACKAGE_PIN R26 [get_ports Scan_Out]
set_property IOSTANDARD LVCMOS33 [get_ports B_Serial]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_Main]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_Scan]
set_property IOSTANDARD LVCMOS33 [get_ports Cout]
set_property IOSTANDARD LVCMOS33 [get_ports Scan_Enable]
set_property IOSTANDARD LVCMOS33 [get_ports Scan_Out]
set_property IOSTANDARD LVCMOS33 [get_ports Sum]
set_property PACKAGE_PIN N24 [get_ports Scan_Enable]
set_property IOSTANDARD LVCMOS33 [get_ports A_Serial]
set_property PACKAGE_PIN D5 [get_ports Clock_Main]
set_property PACKAGE_PIN H6 [get_ports Clock_Scan]

set_property DRIVE 12 [get_ports Cout]

set_property OFFCHIP_TERM NONE [get_ports Cout]
set_property PACKAGE_PIN M22 [get_ports Cout]
set_property PACKAGE_PIN N19 [get_ports Sum]
